/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedNovoPedidoRouteImport } from './routes/_authenticated/novo-pedido'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedEntregadorRouteImport } from './routes/_authenticated/entregador'
import { Route as AuthenticatedDevRouteImport } from './routes/_authenticated/dev'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEntregadorIndexRouteImport } from './routes/_authenticated/entregador.index'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated/pedidos.$id'
import { Route as AuthenticatedPedidosIdDisputaRouteImport } from './routes/_authenticated/pedidos.$id.disputa'
import { Route as AuthenticatedPedidosIdAvaliarRouteImport } from './routes/_authenticated/pedidos.$id.avaliar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovoPedidoRoute = AuthenticatedNovoPedidoRouteImport.update({
  id: '/novo-pedido',
  path: '/novo-pedido',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntregadorRoute = AuthenticatedEntregadorRouteImport.update({
  id: '/entregador',
  path: '/entregador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevRoute = AuthenticatedDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntregadorIndexRoute =
  AuthenticatedEntregadorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEntregadorRoute,
  } as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPedidosRoute,
} as any)
const AuthenticatedPedidosIdDisputaRoute =
  AuthenticatedPedidosIdDisputaRouteImport.update({
    id: '/disputa',
    path: '/disputa',
    getParentRoute: () => AuthenticatedPedidosIdRoute,
  } as any)
const AuthenticatedPedidosIdAvaliarRoute =
  AuthenticatedPedidosIdAvaliarRouteImport.update({
    id: '/avaliar',
    path: '/avaliar',
    getParentRoute: () => AuthenticatedPedidosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dev': typeof AuthenticatedDevRoute
  '/entregador': typeof AuthenticatedEntregadorRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/novo-pedido': typeof AuthenticatedNovoPedidoRoute
  '/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRouteWithChildren
  '/entregador/': typeof AuthenticatedEntregadorIndexRoute
  '/pedidos/$id/avaliar': typeof AuthenticatedPedidosIdAvaliarRoute
  '/pedidos/$id/disputa': typeof AuthenticatedPedidosIdDisputaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dev': typeof AuthenticatedDevRoute
  '/home': typeof AuthenticatedHomeRoute
  '/novo-pedido': typeof AuthenticatedNovoPedidoRoute
  '/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRouteWithChildren
  '/entregador': typeof AuthenticatedEntregadorIndexRoute
  '/pedidos/$id/avaliar': typeof AuthenticatedPedidosIdAvaliarRoute
  '/pedidos/$id/disputa': typeof AuthenticatedPedidosIdDisputaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dev': typeof AuthenticatedDevRoute
  '/_authenticated/entregador': typeof AuthenticatedEntregadorRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/novo-pedido': typeof AuthenticatedNovoPedidoRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/pedidos/$id': typeof AuthenticatedPedidosIdRouteWithChildren
  '/_authenticated/entregador/': typeof AuthenticatedEntregadorIndexRoute
  '/_authenticated/pedidos/$id/avaliar': typeof AuthenticatedPedidosIdAvaliarRoute
  '/_authenticated/pedidos/$id/disputa': typeof AuthenticatedPedidosIdDisputaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dev'
    | '/entregador'
    | '/home'
    | '/novo-pedido'
    | '/pedidos'
    | '/perfil'
    | '/pedidos/$id'
    | '/entregador/'
    | '/pedidos/$id/avaliar'
    | '/pedidos/$id/disputa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dev'
    | '/home'
    | '/novo-pedido'
    | '/pedidos'
    | '/perfil'
    | '/pedidos/$id'
    | '/entregador'
    | '/pedidos/$id/avaliar'
    | '/pedidos/$id/disputa'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dev'
    | '/_authenticated/entregador'
    | '/_authenticated/home'
    | '/_authenticated/novo-pedido'
    | '/_authenticated/pedidos'
    | '/_authenticated/perfil'
    | '/_authenticated/pedidos/$id'
    | '/_authenticated/entregador/'
    | '/_authenticated/pedidos/$id/avaliar'
    | '/_authenticated/pedidos/$id/disputa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novo-pedido': {
      id: '/_authenticated/novo-pedido'
      path: '/novo-pedido'
      fullPath: '/novo-pedido'
      preLoaderRoute: typeof AuthenticatedNovoPedidoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregador': {
      id: '/_authenticated/entregador'
      path: '/entregador'
      fullPath: '/entregador'
      preLoaderRoute: typeof AuthenticatedEntregadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev': {
      id: '/_authenticated/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof AuthenticatedDevRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregador/': {
      id: '/_authenticated/entregador/'
      path: '/'
      fullPath: '/entregador/'
      preLoaderRoute: typeof AuthenticatedEntregadorIndexRouteImport
      parentRoute: typeof AuthenticatedEntregadorRoute
    }
    '/_authenticated/pedidos/$id': {
      id: '/_authenticated/pedidos/$id'
      path: '/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedPedidosRoute
    }
    '/_authenticated/pedidos/$id/disputa': {
      id: '/_authenticated/pedidos/$id/disputa'
      path: '/disputa'
      fullPath: '/pedidos/$id/disputa'
      preLoaderRoute: typeof AuthenticatedPedidosIdDisputaRouteImport
      parentRoute: typeof AuthenticatedPedidosIdRoute
    }
    '/_authenticated/pedidos/$id/avaliar': {
      id: '/_authenticated/pedidos/$id/avaliar'
      path: '/avaliar'
      fullPath: '/pedidos/$id/avaliar'
      preLoaderRoute: typeof AuthenticatedPedidosIdAvaliarRouteImport
      parentRoute: typeof AuthenticatedPedidosIdRoute
    }
  }
}

interface AuthenticatedEntregadorRouteChildren {
  AuthenticatedEntregadorIndexRoute: typeof AuthenticatedEntregadorIndexRoute
}

const AuthenticatedEntregadorRouteChildren: AuthenticatedEntregadorRouteChildren =
  {
    AuthenticatedEntregadorIndexRoute: AuthenticatedEntregadorIndexRoute,
  }

const AuthenticatedEntregadorRouteWithChildren =
  AuthenticatedEntregadorRoute._addFileChildren(
    AuthenticatedEntregadorRouteChildren,
  )

interface AuthenticatedPedidosIdRouteChildren {
  AuthenticatedPedidosIdAvaliarRoute: typeof AuthenticatedPedidosIdAvaliarRoute
  AuthenticatedPedidosIdDisputaRoute: typeof AuthenticatedPedidosIdDisputaRoute
}

const AuthenticatedPedidosIdRouteChildren: AuthenticatedPedidosIdRouteChildren =
  {
    AuthenticatedPedidosIdAvaliarRoute: AuthenticatedPedidosIdAvaliarRoute,
    AuthenticatedPedidosIdDisputaRoute: AuthenticatedPedidosIdDisputaRoute,
  }

const AuthenticatedPedidosIdRouteWithChildren =
  AuthenticatedPedidosIdRoute._addFileChildren(
    AuthenticatedPedidosIdRouteChildren,
  )

interface AuthenticatedPedidosRouteChildren {
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRouteWithChildren
}

const AuthenticatedPedidosRouteChildren: AuthenticatedPedidosRouteChildren = {
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRouteWithChildren,
}

const AuthenticatedPedidosRouteWithChildren =
  AuthenticatedPedidosRoute._addFileChildren(AuthenticatedPedidosRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDevRoute: typeof AuthenticatedDevRoute
  AuthenticatedEntregadorRoute: typeof AuthenticatedEntregadorRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNovoPedidoRoute: typeof AuthenticatedNovoPedidoRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDevRoute: AuthenticatedDevRoute,
  AuthenticatedEntregadorRoute: AuthenticatedEntregadorRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNovoPedidoRoute: AuthenticatedNovoPedidoRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
